# Generated by Django 3.0 on 2019-12-06 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mtg_deckbuilder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='finished',
        ),
        migrations.AddField(
            model_name='deck',
            name='text',
            field=models.CharField(default='assdfsgsdfsadsdg', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
